

# This file was *autogenerated* from the file data-to-txtfile.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3)
load("assemble_data.sage")

curves_by_zeta = defaultdict(list)
for (counts, isom_order, isom_type, stratum, eqn) in curves:
    curves_by_zeta[counts].append((isom_order, isom_type, stratum, eqn))

with open('lmfdbgenus6_curves_F2.txt', 'w') as file: 
    R = ZZ['x, y']; (x, y,) = R._first_ngens(2)
    for counts in curves_by_zeta:
        weil_poly = weil_poly_from_point_count(counts, _sage_const_6 )
        label = label_from_weil_poly(weil_poly)
        curves = curves_by_zeta[counts]
        jacobian_count = len(curves)
        hyp_count = sum([_sage_const_1  for curve in curves if 'hyperelliptic' in curve])
        equations = [latex(R(curve[_sage_const_3 ])) for curve in curves]
        formatted_equations = "{{{}}}".format(", ".join(equations))
        print(formatted_equations)
        file.write('{}|1|{}|{}|{}'.format(label, jacobian_count, hyp_count, formatted_equations))
        file.write('\n')
        

