#!/bin/sh
touch 1.txt 2.txt 3.txt 4.txt 5.txt
magma -b InputFileName:=1.txt ../curves_by_ramification.m &
magma -b InputFileName:=4.txt ../curves_by_ramification.m &
magma -b InputFileName:=2.txt ../curves_by_ramification.m &
magma -b InputFileName:=3.txt ../curves_by_ramification.m &
magma -b InputFileName:=5.txt ../curves_by_ramification.m &
