

# This file was *autogenerated* from the file genus6_moduli_count.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
import os
import sys
import ast

def count_lines_in_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.read().split('\n')
        nonstacky_count = _sage_const_0 
        stacky_count = _sage_const_0 
        error_count = _sage_const_0 

        for line in lines[:-_sage_const_1 ]: 
            nonstacky_count += _sage_const_1 
            tmp = ast.literal_eval(line)
            if 'error' in tmp:
                error_count += _sage_const_1 
                #magma.load(func_path+'auto_group_check.m')
                #//stacky_count += 1/Integer(magma.function_call('count_atoms', tmp[0]))
                print(tmp, file_path)
            else: 
                if tmp[_sage_const_1 ] > _sage_const_1 :
                    print(tmp)
                stacky_count += _sage_const_1 /Integer(tmp[_sage_const_1 ])
        return [nonstacky_count, stacky_count, error_count]

def sum_lines_in_directory(directory_path):
    total_lines = [_sage_const_0 , _sage_const_0 , _sage_const_0 ]

    # Iterate through all files in the directory
    for filename in os.listdir(directory_path):
        file_path = os.path.join(directory_path, filename)

        # Check if the file is a text file
        if os.path.isfile(file_path) and filename.endswith('.txt') and 'problematic' not in filename:
            counts = count_lines_in_file(file_path)
            total_lines[_sage_const_0 ] += counts[_sage_const_0 ]
            total_lines[_sage_const_1 ] += counts[_sage_const_1 ]
            total_lines[_sage_const_2 ] += counts[_sage_const_2 ]

    return total_lines

# Replace 'your_directory_path' with the path to your directory
directory_path = sys.argv[_sage_const_1 ]
func_path = directory_path.strip('sorted_data')
total_lines = sum_lines_in_directory(directory_path)

print(f'Total number of lines in all text files in {directory_path}: {total_lines}')

